### ISSUE TITLE
Enable Github Sponsors?

### ISSUE THREAD

**Issue by broofa** [uuidjs/uuid#384]
[Filing this as an issue so the conversation is public.  Anyone with an opinion should feel free to comment.]

@ctavan: Thoughts on adding a [sponsor button](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)?

I realize this may be an awkward conversation but I figured I'd put it out here just to get people's thoughts.  Also, I'm both impressed and grateful for all the work you've put in recently, and I'd like to make sure you stay happy and motivated here moving forward.   And, of course, I have my own slightly selfish motivations...

Pros:
- Frankly, experience has taught me that maintaining this lib can be a bit of thankless task.  On a years-long timescale, providing support as Life Happens can be draining at times.  (E.g. I've had a kid, divorced, remarried, and changed jobs 3 times since starting this project 😄).  Regardless of the actual $-amount involved, donations are tangible proof that what you're doing has value, and I expect that would be a nice perk to help with motivation.
- I'm genuinely curious how the recent trend in patronage / sponsorships of opensource projects actually works.  This would be an interesting experiment.

Cons:
- Not really sure there is any but... there's a bit of a Heisenbergian-effect around money.  You can't really monetize something without affecting the underlying value dynamics.  I'm not sure how or if this would impact how this project is perceived, or cast suspicion on our motivations (e.g. with the Standard Uuid Module work.)

**Comment by ctavan** [comment]
This is an interesting suggestion I haven't really considered so far. While I'm currently in the lucky situation that I can dedicate enough of my spare time to work on this module and I don't expect to earn money during that time I would certainly find it interesting to learn more about opportunities in that direction. After all I have put more than half a month worth of nominal working time into this project and the uuid standard library proposal over the past 10 months.

That said I don't have the slightest clue how these sponsorship systems work in practice, what the terms are, what platform/tool we should use etc. Did you go down this rabbit hole already?

The only condition for me would be to be 100% transparent about the amounts and distribution of money.

If this condition can be met I don't see reason why we should not try it out. If it turns out to push the project into a bad direction we can still remove sponsorship again and continue just like in the previous decade 😉

**Comment by broofa** [comment]
> Did you go down this rabbit hole already?

Only insofar as I got an email from Github about their [Sponsors](https://github.com/sponsors) program and went through the signup process (more for curiosity than anything else.)  It's pretty easy to do, and the end result is a "Sponsor" button on my Github profile that lands people [here](https://github.com/sponsors/broofa).  I'm not actively promoting that however so there hasn't been any activity, not unsurprisingly.

I've also noticed a couple opensource projects adding sponsorship links to their homepages.  E.g. https://mochajs.org/#sponsors.  I guess I'm of the mind that, to the extent Github makes this sort of thing easy, I don't see any reason not to try it out.  If you're open to the idea, I can put a PR together.

I dunno... honestly, I wouldn't expect too much to come of it.  Like I said, I would mostly treat this as an experiment in how opensource sponsorships work.

**Comment by broofa** [comment]
![image](https://media0.giphy.com/media/5hgIExulbZSIq04lLh/giphy.gif)

**Comment by ctavan** [comment]
So you changed plans?

**Comment by broofa** [comment]
Reviewing the issues and we (well, I, really) hadn't done anything with this so... 🤷
