### ISSUE TITLE
What happened to this package???

### ISSUE THREAD

**Issue by azamsharp** [uuidjs/uuid#414]
This used to be a great package but now the whole usage is lost in docs. I have no idea how to use it. I just installed: 

"uuid": "^7.0.3"

How do I use it in node?

**Comment by ctavan** [comment]
What exactly is not clear? Have you seen https://github.com/uuidjs/uuid#quickstart---nodejscommonjs ?

If `import`-syntax is the problem then you can find an example of how to use `require()` syntax in - https://github.com/uuidjs/uuid#deep-requires-now-deprecated .

**Comment by ctavan** [comment]
Since I haven't heard back from you I will close this issue.

If you think that the documentation doesn't cover your needs please feel free to suggest improvements via a pull request.

**Comment by Raynos** [comment]
I have the exact smae problem as the original issue opener.

I just installed uuid like I've done for years with the v3.x range.

The documentation has `import` / `export` which is not valid for my codebase and no example of how to use `require`

The examples of using `require` are all the way at the bottom of the README and since there's no good example after scrolling one or two pages I just

(╯°□°)╯︵ ┻━┻

It would be super useful to show an example using `require` & `import` at the top of the README.

**Comment by ctavan** [comment]
Although I believe that explaining the difference between CommonJS `require` syntax and ECMAScript Module `import` syntax is out of scope for this library, we have added an example of how to use the library with `require` in a more prominent position in the readme.

Thanks for the contribution @Raynos!

**Comment by Raynos** [comment]
You are one of the first of my dependencies migrating to ESM. 

I believe my frustrations are with ESM and not with uuid itself, your just an early adopter.
