### ISSUE TITLE
question, possible uuid collision

### ISSUE THREAD

**Issue by sundowndev** [uuidjs/uuid#420]
Hi, I've seen some projects doing this with this package: `v4().substr(0, 10)` to only take the 10 first characters of the UUID.

Is this creating a risk of collision ?

**Comment by LinusU** [comment]
Yes.

You are only getting 9 hexadecimal characters of randomness (9 because one of the 10 will always be `-`)

<img width="720" alt="Screenshot 2020-04-22 at 15 18 34" src="https://user-images.githubusercontent.com/189580/79993322-8b07b180-84ac-11ea-87ad-cc68311b2666.png">

ref: https://zelark.github.io/nano-id-cc/

**Comment by ctavan** [comment]
Nice tool, thanks for making me aware of that one @LinusU !

**Comment by sundowndev** [comment]
Thank you @LinusU 👍 

Do you know a way to safely generate short timestamp-based UUIDs ? Like 10 chars, growing as of time.

**Comment by LinusU** [comment]
It's really hard to make a recommendation without knowing the full requirements and usage scenario.

With 10 characters and base64 encoding you can get 60bits of data. You then need to decide how much many bits you want to give to the date part, and how much to the random part.

e.g. if you split it 30bits to specify number of seconds since 2020-01-01, and 30 bits to randomness you should be able to generate a few ids every second (~4600 in the same second would result in a 1% chance of collision) until the year 2050.

(disclaimer: I did not double check my math here)

Anyhow, I think that this is out of scope for the uuid module, so I will close this issue. But I will continue to answer if you post anything more :)

**Comment by broofa** [comment]
At the risk of being pedantic, a "10 char UUID" is an oxymoron.  "UUID" has a very specific definition (see RFC 4122). tl;dr - they have exactly 32 hex characters. No more, no less.

There are many libraries out there for generating unique IDs of various flavors.  E.g. `nanoid` and `shortid`.  Just be aware that you're venturing into "non-standard" territory and don't expect such IDs to play nice in contexts that expect RFC-standard UUIDs.

**Comment by sundowndev** [comment]
Alright thanks for the details. I was just wondering how could I generate youtube-like IDs (`/watch?v=gnV-8pkILF0`). Do you have any idea about that?

**Comment by LinusU** [comment]
How many id:s are you going to generate?

<img width="723" alt="Screenshot 2020-04-23 at 08 11 18" src="https://user-images.githubusercontent.com/189580/80069895-05324780-853a-11ea-9060-959217d2b13d.png">

Using `nanoid(11)` will produce IDs that looks exactly like the YouTube ones. But I have a feeling that they are using some sort of coordination to make sure that collisions never happen. 

I think that they are encoding a 64-bit integer, which is what Twitter is using as well: https://developer.twitter.com/en/docs/basics/twitter-ids

Here you can read a bit about how they solved it: https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html

**Comment by sundowndev** [comment]
>Just be aware that you're venturing into "non-standard" territory and don't expect such IDs to play nice in contexts (like databases) that have built-in support for UUIDs.

Not if I simply use base64 as I mentioned above, right?

>But I have a feeling that they are using some sort of coordination to make sure that collisions never happen.

Yes. I think the length grows as of time, that's why I was asking. Thanks for pointing out nanoid tho, it has an implementation in several languages.

**Comment by broofa** [comment]
> Not if I simply use base64 as I mentioned above, right?

No.  UUIDs are not base64 encoded.
