### ISSUE TITLE
Version 8.1  won't load using legacy require('uuid/v4')

### ISSUE THREAD

**Issue by edgework** [uuidjs/uuid#456]
For some reason the v4.js ,v3.js etc files were removed  (in 8.x?)  and now code that's worked fine for a long time no longer works because it was written before `const { v4: uuidv4 } = require('uuid');` was a thing and  `require('uuid/v4')`  was the way to do it.     And its not like I can just go though 300+ files in multiple projects and just change it  oh and some of this still needs to run on older versions of node due to circumstances out of my control.  And yes I can just lock down the version to 7.x but in a large development group just tweaking a global file like package.json requires sign off etc. and all the while builds are halted while we go on a fire drill  so please realize you're not in a bubble and willy nilly remove stuff because its old or whatever.

**Comment by LinusU** [comment]
I don't really understand why you would have to go and change it in multiple projects, and that the builds are currently breaking until you do so. When you `npm install` a package it will be saved with a caret (`^`) by default, which will not bring in any breaking changes.

If you are globally pulling in the latest version of your dependencies, then surely you are going to have this problem any time any package release a breaking change?

Are you suggesting that we never make breaking changes? 🤔 

Genuinely curious about your setup! Would appreciate some more information

**Comment by edgework** [comment]
uuid was one of those modules that is so simple (supposedly) that  using "*" for the version was thought a good idea to keep it up to date.  No one ever thought for something so simple the method of loading the module would be changed and the old way completely deprecated.

Why is is so important to remove the backwards compatibility file so people don't have to change their code just to be up to date?  In tight code control environments,  managers don't like code changes for no apparent reason other than style which is what this is. Its not clear, and again unexpected, that such a simple library would need to make a breaking change to requiring it.

**Comment by ctavan** [comment]
We are using the https://semver.org/ versioning convention. We take great care to ensure that breaking API changes only occur with major version changes and this is what happens.

The ecosystem evolves and libraries evolve alongside the ecosystem. At the time when this library was initially released [almost a decade ago](https://github.com/uuidjs/uuid/tree/v1.0) ECMAScript modules with [`import/export` syntax were far from being a thing](https://gist.github.com/jkrems/769a8cd8806f7f57903b641c74b5f08a). Once browser support for the library was added, bundlesize suddenly became a thing, and the only way to reliably solve this issue were deep require paths.

Now that ECMAScript modules are a well-supported standard that support static tree shaking and solve the bundlesize problem for the browser it was about time to revert this workaround and prepare this library for the future. For library authors each additional piece of API surface means additional work and since we all work on this in our unpaid free time we therefore thrive to keep the API surface of this library as small as possible.

To cite the [first sentence of the semver spec](https://semver.org/):

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> 1. MAJOR version when you make incompatible API changes,

The very reason why semver exists is to allow library authors to make incompatible API changes. If you decide not to rely on these guarantees then this was your deliberate choice.

**Comment by broofa** [comment]
> using "*" for the version was thought a good idea

![image](https://i.giphy.com/media/GDnomdqpSHlIs/giphy.webp)

**Comment by LinusU** [comment]
> uuid was one of those modules that is so simple (supposedly) that using "*" for the version was thought a good idea to keep it up to date.

I would say that this is never a good idea. With the same logic, you could have thought that "the module was so simple so it will never have a breaking change", and thus you could have pinned it at `^1.0.0`...

The fix here is simple, never use `"*"` for your dependencies, as that will introduce the kinds of problem that you posted about. That goes for all dependencies...
