### ISSUE TITLE
add fromString method alternative

### ISSUE THREAD

**Issue by correttojs** [uuidjs/uuid#520]
I'd like to migrate from `uuidv4`, as suggested in that repo. 
I'm using the function `fromString` which doesn't exist in this repo. I see the `uuid.v4()` function accepts several options, but I don't see a way to create a uuid given a string. 
Could you provide this functionality or document it if already available?

**Comment by ctavan** [comment]
What exactly are you trying to achieve? Do you want to convert a string representation of a `UUID` into a byte array? Then [`uuid.parse()`](https://github.com/uuidjs/uuid#uuidparsestr) is your friend.

**Comment by correttojs** [comment]
given a unique string (i.e. a user identifier), I would like to generate always the same uuid

**Comment by broofa** [comment]
@correttojs The deprecation message warning provided by `uuidv4` tells you (mostly) how to do this - use the `v5()` method.  E.g.
```
import {v5 as uuidv5} from 'uuid';

uuidv5('string to create uuid from', 'bb5d0ffa-9a4c-4d7c-8fc2-0a7d2220ba45');
```

(@ctavan: `uuidv4`'s `fromString()` method is a wrapper around v5 namespace uuid creation.  [See source](https://github.com/thenativeweb/uuidv4/blob/master/lib/uuidv4.ts#L31-L34).)

The one fiddly bit is the custom namespace ("bb5d0ffa-...")  you need to provide if you care about backward compatibility with previously generated `fromString()` ids.  Otherwise you can use `uuidv5.DNS` or `uuidv5.URL` instead, or create your own namespace id [as described in our docs](https://github.com/uuidjs/uuid#uuidv5name-namespace-buffer-offset).

Cc: @goloroden for possible improvements to deprecation / migration instructions in `uuidv4` codebase.

**Comment by correttojs** [comment]
that would cover my case, thank you!
indeed I saw a deprecation warning in `uuidv4`, but it was only related to the `isUuid` method. It would be nice to add one as well for the `fromString` method

**Comment by goloroden** [comment]
Thanks for the hint! I think we'll update the docs sooner or later, and phase out the module entirely.

**Comment by ctavan** [comment]
Closing in favor of https://github.com/thenativeweb/uuidv4/issues/219 since there's nothing actionable on our end.
