### ISSUE TITLE
IE11 support broken since 8.3

### ISSUE THREAD

**Issue by Mairu** [uuidjs/uuid#523]
## Describe the bug

Since version 8.3 the lib does not work in IE11.

## How to reproduce

Load the lib in IE11

## Expected behavior

It should work in IE11

## Runtime

- OS: Window
- Runtime: IE11
- Runtime Version: 11.508.19041.0

## Additional information

The Problem is, that IE11 does not support default values for function parameters, which is used in https://github.com/uuidjs/uuid/pull/479/files#diff-016d740d7835ede8d0af47fe304f7191R13

**Comment by Mairu** [comment]
Ok, it is a problem of meteor not using the esm-browser version when importing it.

**Comment by ctavan** [comment]
I guess it's a duplicate of #516: If your bundler is configured to prefer CommonJS versions of a module over ESM, you might get problems in IE11.

We could technically fix it, but I'm a bit reluctant of introducing a new special build just to support the CommonJS w/ IE11 special case. When bundling for the browser, using the CommonJS build is not ideal anyways since you will always get the full UUID module instead of just the bits that you need.
