### ISSUE TITLE
Support Stable Storage

### ISSUE THREAD

**Issue by yuanchieh-cheng** [uuidjs/uuid#538]
## Is your feature request related to a problem? Please describe.

When I read the [doc #4.2.1.1](https://tools.ietf.org/html/rfc4122#page-8), it suppose that implementation should store clock_seq , timestamp , Node id to system-wide stable storage.  
```
   If an implementation does not have any stable store available, then
   it can always say that the values were unavailable.  This is the
   least desirable implementation because it will increase the frequency
   of creation of new clock sequence numbers, which increases the
   probability of duplicates.
```

When I read the source code, it default generate randomly all the time or user have to deal with this on their own.  

## Describe the solution you'd like

Is it possible to support stable storage as built in option ?

## Describe alternatives you've considered

Randomly generating every time is OK.  
Just wonder the impacted collision possibility.

**Comment by ctavan** [comment]
We intentionally initialize clock sequence and node ID lazily once per JavaScript process lifetime:

https://github.com/uuidjs/uuid/blob/334ef62c330d92f8ca376d09087e8ee9abc5cc12/src/v1.js#L25-L47

I believe that this comes close to the idea of the spec while avoiding the [privacy problems](https://github.com/tc39/proposal-uuid#are-there-privacy-concerns-related-to-v1-uuids) that come with trying to derive a stable node ID from hardware.

Given that in our implementation the node ID changes with each initialization of the clock sequence, I think that the concern that you quote from the RFC does not apply: Generating new clock sequences frequently would only be a problem if the node ID was stable.

You can find more details [in this discussion of v1 UUID uniqueness](https://github.com/tc39/proposal-uuid#arent-v1-uuids-better-because-they-are-guaranteed-to-be-unique).

**Comment by yuanchieh-cheng** [comment]
Thanks for your reply.  
It's really detailed and helpful for me to understand the design.
