### ISSUE TITLE
Exception has occurred: TypeError: Cannot assign to read only property 'name'... 

### ISSUE THREAD

**Issue by justuscook** [uuidjs/uuid#564]
## Describe the bug

```
Exception has occurred: TypeError: Cannot assign to read only property 'name' of function 'function generateUUID(value, namespace, buf, offset) {
    if (typeof value === 'string') {
      value = strin...<omitted>... }'
```

## How to reproduce
I'm not what to put here, this is throwing the error referencing my main JS file, but that file has no reference to the uuid functions.

## Expected behavior
To not give this error lol.

## Runtime
Node.js 14.15.5

**Comment by TrySound** [comment]
This is weird. We have guard for this. https://github.com/uuidjs/uuid/blob/master/src/v35.js#L57-L61
Which version of uuid do you use?

**Comment by justuscook** [comment]
I just releaized the try catch in the lib, i had caught exception on in my bebugger, my apologies.

**Comment by Duckers** [comment]
Is this really necessary? Even when not using v35 I get this super annoying error all the time when running with debugger

**Comment by broofa** [comment]
> Is this really necessary?

Good question.  The try-catch was added to address #268.

As for why `name` is set, that was added at my request in the original PR to "Set function name shown in debuggers". See https://github.com/uuidjs/uuid/pull/217#issuecomment-326404919.   Without this, `v3` and `v5` would both show up in stacktraces as `generateUUID`.

I.e. it's basically for cosmetic reasons when debugging code that calls `v3` or `v5` and is not strictly necessary.

... and relatively few people use `v3` or `v5`.  (I think it's something like 1% of uuid users?)

That said...

>  Even when not using v35 I get this super annoying error all the time when running with debugger

1. If you're not using v35 and you're code uses ESM imports, a tree shaking bundler (e.g. parcel/rollup/webpack) should remove this code. 

2. This code is only called (twice) on module load, not each time a uuid is created.  And if you've set your debugger to pause on *caught* exceptions (which is the only time this is an issue, right?) I expect this is hardly the only place you're running into this issue.  Wrapping feature-specific code in a try-catch is standard practice.  It's done all the time, in all sorts of modules.  While I agree it's frustrating (on the rare occasions there is reason to break on caught exceptions), the problem is by no means specific to `uuid`.  I.e. It kinda comes with the territory.

**Comment by rezshek** [comment]
> Is this really necessary? Even when not using v35 I get this super annoying error all the time when running with a debugger

Same here, any way around it?
I'm trying to connect to Cosmos DB with @azure/client and this is what happens as soon as I hot the API that I have there.

**Comment by LarryStewart2022** [comment]
Exception has occurred: TypeError: Cannot assign to read only property 'name' of function 'function generateUUID(value, namespace, buf, offset) {
    var _namespace;

    if (typeof value === 'string') ...<omitted>... }'
  at v35 (C:\LANGCHAIN\node_modules\uuid\dist\v35.js:73:23)
    at Object.<anonymous> (C:\LANGCHAIN\node_modules\uuid\dist\v3.js:14:27)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\LANGCHAIN\node_modules\uuid\dist\index.js:63:34)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
