### ISSUE TITLE
Count test on uniformity of occurrence in uuid (hex)

### ISSUE THREAD

**Issue by emclab** [uuidjs/uuid#593]
## Is your feature request related to a problem? Please describe.

Here reported is a test result. The purpose of count test is to see if uuid alg favors/dislike certain letter or number by counting the occurrence of each letter/number in uuid (8.3.2. hex) generated. There are total of 10000 uuids generated and counted. Here is the code in reactjs (17.0.2)/nodejs 14.17.0 for the test:

```
import { v4 as uuidv4 } from 'uuid';
let round = 10000, temp1, objuuid={};
for (let i=0;i<round;i++) {
            console.log("ith round : ", i);
            temp1 = uuidv4(); //uuid generated
            //uuid
            for (let j=0;j<temp1.length;j++) {
                let a1 = temp1.charAt(j);
                if (a1 !== "-") {. //don't count "-"
                    let hit = false;
                    Object.keys(objuuid).map(k => {
                        if (k == a1) {
                            hit = true;
                            //break;
                        }
                    });
                    if (hit) {
                        objuuid[a1] = objuuid[a1] + 1;
                    } else {
                        objuuid[a1] = 1;
                    }
    
                }
            }
        };
```

Here is output of objuuid in 3 run:

1st one:

0: 18934
1: 18723
2: 18789
3: 18712
4: 28840
5: 18491
6: 18628
7: 18732
8: 21498
9: 21241
a: 21238
b: 21223
c: 19003
d: 18820
e: 18492
f: 18636

2nd one:

0: 18768
1: 18837
2: 18572
3: 18945
4: 28557
5: 18908
6: 18922
7: 18734
8: 21265
9: 21044
a: 21274
b: 21344
c: 18681
d: 18604
e: 18775
f: 18770

3rd one:

0: 18676
1: 18743
2: 18712
3: 18741
4: 28722
5: 18947
6: 18747
7: 18736
8: 21316
9: 21253
a: 21111
b: 21413
c: 18795
d: 18704
e: 18737
f: 18647

From the result above (did more than 3 runs), It seems that "4, 8 ,9 , a,  b" are more favored than others. Will this "favor" negatively impact the security of the uuid generated?  Is the bias more related to PRNG used in reactjs/nodejs (crypto.getRandomBytes?)?

**Comment by broofa** [comment]
This is expected.  The 13th character is the `version` field and will always be "4" for version 4 uuids.  The 17th character contains the `variant` field and will always be `[89ab]`.  See https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.2 for details.

**Comment by emclab** [comment]
Hi `broofa`, does this make the uuid generated a bit easier to be guessed?

**Comment by broofa** [comment]
In theory, yes.  Having 128 bits of randomness is harder to guess than 122 bits.

In practice, there are two things you need to know.  The first is that UUIDs are [not meant to be unguessable](https://datatracker.ietf.org/doc/html/rfc4122#section-6).  If you're really concerned about *security*, use actual  technology designed to be _secure_.  UUIDs aren't that.

The second is that UUIDs are actually pretty hard to guess.  "How hard", you ask?  Well, let's try a fun little thought exercise ...

----

***I've just handed you a 1,000TB  SSD filled with UUIDs.  I.e. More than you are ever likely to generate by many, many orders of magnitude.  How long would it take to guess just one of the UUIDs on this drive?***

For your first attempt you figure that's a lot of UUIDs.  Surely it can't be that hard, right?  So let's just guess one and see if it's on the drive.

Hmm, this is taking a while.  Like, a _long_ while.  Why is it taking so long?  Oh, right, SSDs can only read at a rate of 550MB/second.  So just checking a single number is going to take... <crunches numbers>... 21 days.  Wow, we really do have a lot of UUIDs here, don't we?

Okay, fuck that approach.  This is what databases and db indexes are for.  SQLite to the rescue!  It can do [5,000 checks/second](https://sqlite.org/speed.html) on indexed data, so let's give that a try.  (Ignoring for the moment that SQLites' theoretical max db size caps out at [a paltry 281 TB](https://www.sqlite.org/limits.html).)  So slurp all the UUIDs into the DB, build your index and start guessing!

Hmm... this is _still_ taking awhile.  Like, we've been going at this for weeks now and still no luck.  Why isn't this working?  Is there something wrong?  How many guesses is this going to take???

Maybe we should think about this a bit.  <grabs pen and paper>.  Okay, let's say we want a 1-in-a-million chance of guessing just one of the UUIDs out of this now-annoyingly-large dataset we've been given.  That's a pretty modest goal, right?  How many guesses are we talking about?  After [crunching the numbers](https://www.wolframalpha.com/input/?i2d=true&i=Power%5B%5C%2840%29Power%5B%5C%2840%291+-+Divide%5B1%2CPower%5B2%2C122%5D%5D%5C%2841%29%2C62.5e9%5D%5C%2841%29%2C1e19.9%5D), we have an answer: 10<sup>19.9</sup> guesses.

Wow.  That's kind of a lot.  What's are we talking about with this SQLite setup (that is suddenly looking very, very underpowered for this)? Answer: 504M years.

Crap.  We would have had to start this around the time multi-cellular life first appeared on earth to have an answer by now.  Well, at least we know why we haven't been able to guess one of the UUIDs yet.  Clearly we need a different setup.

Let's see how fast can we do this thng? Google currently does about [63,000 queries/second](https://www.google.com/search?q=how+many+queries+per+second+does+google+get) but we know that's nowhere near enough. Let's throw everything we have at this and get to where we can do our checks in the time it takes to [read a single UUID out of RAM](https://en.wikipedia.org/wiki/DDR5_SDRAM), or about 3x10<sup>9</sup>checks/second.  What this system looks like in practice is TBD.  We'd need our DB sharded across a bunch of computers, all loaded up with DDR5 RAM, all networked together.  There might be a cloud-architecture for this that's not too expensive... maybe?

Just keep in mind that we're talking about query performance 100,000X faster than google does searches.  Best case scenario this will be a significant research project that probably nets you a nice little PhD in comp-sci.  Worst case it turns out to be nigh-impossible.  It depends on where the point of diminishing returns is for performance here, which I don't have a good feel for.

But whatever... lets say we build this system. After however much time and $$$, what are we talking about?  Remember, our goal is a modest 1-in-a-million chance of this working.  So how long until we have a slim chance of actually guessing a single UUID...?

Answer: [812 years](https://www.wolframalpha.com/input/?i2d=true&i=Divide%5BPower%5B10%2C19.9%5D%2C%5C%2840%293.1*Power%5B10%2C9%5D%5C%2841%29*365*24*3600%5D)

...

I'm sorry, what was your question?  Something about needing 6 more bits of randomness to make this problem harder...?

(My apologies if this comes across as snarky.  It's not intended that way.  I understand the motivation for your question, and it's a good question to be asking.  But the numbers involved here are so large that our intuition stops working.  It's simply not possible to have an intuitive grasp of how hard or easy it is to guess a UUID at random until you actually crunch the numbers.)
