### ISSUE TITLE
Reduce package size by code splitting

### ISSUE THREAD

**Issue by williazz** [uuidjs/uuid#772]
### Feature description

Thanks for creating UUID. If possible, I would like to reduce the package size by code splitting. Is this in the backlog? 

For example

```
// bad
// the entire package is imported
import { v4 } from 'uuid'

// good
// only imports v4 and necessary dependencies
import v4 from 'uuid/v4'
```

**Comment by broofa** [comment]
> ```js
> // bad
> // the entire package is imported
> import { v4 } from 'uuid'
> ```

The above is the correct syntax, and does in fact allow modern bundlers to "tree shake" out unused code.  (See our `examples` directory for examples of how this works with rollup and webpack.)

If this isn't working for you - i.e. if your bundles contain code for non-v4 versions - please provide a link to a functional example or repository demonstrating the problem and we can take a look.

> ```js
> // good
> // only imports v4 and necessary dependencies
> import v4 from 'uuid/v4'
> ```

This is syntax won't work by design.  We dropped support for deep imports a few major-versions back (v7... or maybe v8?)

**Comment by williazz** [comment]
Sure this my team's repo https://github.com/aws-observability/aws-rum-web

As shown below via `webpack-bundle-analyzer`, we are including other modules such as md5, v1, v3 etc. despite our prod config https://github.com/aws-observability/aws-rum-web/blob/main/webpack/webpack.prod.js

<img width="1753" alt="Screenshot 2024-06-19 at 1 39 57 PM" src="https://github.com/uuidjs/uuid/assets/43121212/cc4010e8-e977-4152-bd39-a5df8244e4cd">

How should this be done instead?

**Comment by williazz** [comment]
I've also reviewed https://webpack.js.org/guides/tree-shaking/#root and can't find any issues. We are using the production build, the default minimizer from TerserPlugin, and have marked zero side effects.

**Comment by broofa** [comment]
'Looks like the problem is that you're transpiling to commonjs, which bundlers aren't able to tree shake.  While this project does provide commonjs builds, we don't provide the ability to deep import specific versions the way you're suggesting.

While I acknowledge that's a flaw in the existing API for CJS use cases, it's not something I'm interested in addressing at this time.

> How should this be done instead? 

Consider bundling for ESM.  Failing that, I'd suggest switching from `uuid` to `[crypto.randomUUID()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)`, which is broadly supported now.

**Comment by williazz** [comment]
Thank you so much for the two strong callouts
1. Compiling to commmon js is breaking our tree shaking
2. Backup strategy to use native crypto package for uuids
