### ISSUE TITLE
v7: allow query timestamp from a uuid v7

### ISSUE THREAD

**Issue by marklai1998** [uuidjs/uuid#777]
### Feature description

can we include a util function that allows retrieving the timestamp from a UUID V7?

**Comment by broofa** [comment]
Parsing UUIDs for timestamp information is [discouraged by the RFC](https://www.rfc-editor.org/rfc/rfc9562.html#section-6.12).  This is in part because UUID timestamps may deviate from actual system clock time ([ref 1](https://github.com/uuidjs/uuid/blob/6e540f3564459a542c3dce1e620d4478c5daf2c1/src/v7.ts#L53-L59), [ref 2](https://github.com/uuidjs/uuid/blob/6e540f3564459a542c3dce1e620d4478c5daf2c1/src/test/v7.test.ts#L175-L186)), which makes them a bit of a foot gun for anyone expecting them to be accurate.

**Comment by marklai1998** [comment]
@broofa I understand, but being discouraged doesn't mean it should be strictly prohibited
especially from a lib standpoint, it should provide the flexibility to do so but also warn the user when using it

I generally found this feature useful when passing UUID through multiple service, I do not have to pass in an extra timestamp, and it's not impacted by the "system time" issue

without this I would have to either append extra timestamp information when transmitting a content with UUIDv7 identifier, and the timestamp might/might not be the same as the UUIDv7, unless I create a timestamp first and use the timestamp to create the UUIDv7
at scale it might be a pain to deal with if someone doesn't follow this convention

**Comment by broofa** [comment]
So... I don't really have time (or energy) to get into an extended discussion about this.  Suffice it to say that the `timestamp` field is best thought of as a counter that happens to correlate well to system time... _usually... but not always_.  And it's that last part, that little "not always" caveat that is the reason it's use as a bonafide timestamp is discouraged.

For now, I think the best path forward would be for you or someone else to implement and publish this as a standalone module.  If / when it gets significant traction and the use cases for it are better understood, we can look at adding support here.

**Comment by marklai1998** [comment]
understand, thanks for your time
