### ISSUE TITLE
[BUG] Source map generation - file not found warning

### ISSUE THREAD

**Issue by jbpenrath** [uuidjs/uuid#826]
### Before you begin...

- [X] I have searched the existing issues
- [X] I am not using version 13.x of node  (if so, please upgrade)

### Description of the problem

Since the version 11.0.x, I get warnings related to `uuid` when generating source map at build. To build my project I'm using `webpack` so the package `source-map-loader` is used to generate source maps.

Here it is an example of warning I got : 

```
WARNING in ./node_modules/uuid/dist/esm-browser/v6ToV1.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/jbpenrath/dev/github/openfun/richie/src/frontend/node_modules/uuid/src/v6ToV1.ts' file: Error: ENOENT: no such file or directory, open '/Users/jbpenrath/dev/github/openfun/richie/src/frontend/node_modules/uuid/src/v6ToV1.ts'
 @ ./node_modules/uuid/dist/esm-browser/index.js 11:0-48 11:0-48
 @ ./js/widgets/LtiConsumer/index.tsx 24:0-36 51:19-25
 @ ./js/widgets/index.tsx 46:9-38
 @ ./js/index.tsx 48:0-31 183:42-46
```

It seems `source-map-loader` is looking for some files located in the `src` folder but this directory is not embedded in the package so the type file is not found.

I wonder if this is not related to the `inlineSourceMap` option enabled in your tsconfig.

**Comment by broofa** [comment]
There's something weird with your project configuration.  That error is complaining about a missing `uuid` source file in node_modules directory ("...node_modules/uuid/src/v6ToV1.ts").

[`uuid` doesn't install any src/* files.](https://www.npmjs.com/package/uuid?activeTab=code)

You need to actually **install* `uuid` to get source maps (which are provided inline in the dist/* files).

**Comment by jbpenrath** [comment]
I just wonder if the source map you are generating are really useful if you don't embedded `src` folder in the released package.

c.f: https://github.com/mswjs/interceptors/pull/204

**Comment by jbpenrath** [comment]
Actually, as `src` folder is not embedded in the released package, `source-map-loader` is not able to consume and parse properly the `sourceMappingUrl` attribute included in `uuid` built files.

To fix the issue, there are two ways IMO :
1. `uuid` embedded `src` folder in the release (like [mswjs/interceptors did](https://github.com/mswjs/interceptors/pull/204) for example)
2. We must tweak your webpack config to tell [`source-map-loader` to skip source map from uuid package](https://www.npmjs.com/package/source-map-loader#filtersourcemappingurl).

**Comment by broofa** [comment]
Ah, sorry, I think I misunderstood.   Reopening for continued discussion.

The error message "Failed to parse source map from '...uuid/src/v6ToV1.ts'" sounds like it's trying to read a source map from a non-existent file.  Are you saying the error instead stems from  not being able to find a file referenced by the source map info?

If so, then the issue here is that this module ships with source maps (inline), but no source... which I agree is a bug.  This means there's one of two options:
1. Include source files
2. Remove sourcemaps

I'm inclined to go with the latter because, historically, this project has not included sourcemaps and I don't recall anyone asking for them.   And in looking in the `node_modules` for one of the larger projects I have access to, I only see sourcemaps in 489 of the 2013 modules (24%).  I.e. Including sourcemaps appears to be the exception rather than the rule.

That uuid@11 includes source maps was a bit of an afterthought.  There was no request for them, nor was there any prolonged discussion about it... and I clearly didn't think it all the way through. So... 🤷 

**So, question:   Where this issue is concerned, would removing sourcemaps altogether address solve your problem?   Or do you really *need* to have the sourcemap information.   If so, why?**

**Comment by vitaliyhan** [comment]
same

**Comment by jbpenrath** [comment]
IMO this is fine to remove sourcemap for now to prevent many questions about this warning and to keep the package size low.

Then you will have to think about source map feature only when someone really needs it.

**Comment by andrewstec** [comment]
I landed here because I started getting warnings about a source map being excluded:

```
WARNING in ../.yarn/cache/uuid-npm-11.0.2-13e156cc62-b98082f398.zip/node_modules/uuid/dist/cjs/v35.js
Module Warning (from ../.yarn/__virtual__/source-map-loader-virtual-33b8eec268/0/cache/source-map-loader-npm-5.0.0-62d48efeee-9bc90a50df.zip/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/spaghetti/repos/food/project/.yarn/cache/uuid-npm-11.0.2-13e156cc62-b98082f398.zip/node_modules/uuid/src/v35.ts' file: Error: ENOENT: no such file or directory, open '/node_modules/uuid/src/v35.ts'
 @ ../.yarn/cache/uuid-npm-11.0.2-13e156cc62-b98082f398.zip/node_modules/uuid/dist/cjs/v3.js 5:17-36 6:15-34
 @ ../.yarn/cache/uuid-npm-11.0.2-13e156cc62-b98082f398.zip/node_modules/uuid/dist/cjs/index.js 16:14-32
 @ ./src/services/bananaService.ts 22:15-30
 @ ./src/routes/exerciseRoutes.ts 13:26-64
 @ ./src/customRoutes.ts 19:41-75
 @ ./src/server.ts 10:23-48

```

<img width="174" alt="image" src="https://github.com/user-attachments/assets/527b1225-c716-48e8-865a-1af0741dd25c">

Is it possible that there is a further convention to remove source maps without it triggering warnings? I am not opinionated on this issue, but you might get a lot of traffic about this issue. I'm not sure why or if it should occur. Webpack's `source-map-loader` could be too opinionated?

**Comment by joshkel** [comment]
@andrewstec The errors were because uuid v11.0.0 through 11.0.2 were built with source maps enabled, and so they distributed JS files that referenced external source maps via `//# sourceMappingURL` comment directives, but, to save space, they omitted the source maps themselves. That's why `source-map-loader` et al. were raising warnings.

Starting with 11.0.3, source maps are disabled, so no more warnings should be logged.

**Comment by andrewstec** [comment]
Thanks! I understand now. Much appreciated!

**Comment by broofa** [comment]
> via //# sourceMappingURL comment directives, but, to save space, they omitted the source maps themselves

To be clear, 11.0.0-11.0.2 had _inline_ source maps.  <img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcG1pazdnbm9ocWJxYnJudmZzajNhNDVodThkcTV6amdldDgzbDg1YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/I2yju3VCw9Ff2/giphy.gif" height="150" align="right" />So the issue wasn't that the source maps were missing, it was that the source files- the `src/*.ts` files - referenced by those source maps were never included... which renders the sourcemaps moot. 

Either way, removing the sourcemaps should fix the problem.  And 11.0.3 is out now, so this is mostly just me looking for an excuse to post memes of apes #PickingNits.
